config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  #static_pages
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  #users
  get    '/signup',  to: 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  #sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  #accountactivations
  resources :accout_activations, only: [:edit]
  #password_resets
  resources :password_resets,    only: [:new, :create, :edit, :update]
  #microposts
  resources :microposts,         only: [:show, :create, :destroy]
  #relationships
  resources :relationships,      only: [:create, :destroy]
  #likes
  resources :likes,              only: [:create, :destroy]
  #comments
  resources :comments,           only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in?
  		@micropost 	= current_user.microposts.build
  		@feed_items = current_user.feed.paginate(page: params[:page]).search(params[:search])

  	end
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>

app/views/static_pages/home.html.erb
<% provide(:form_path, root_path) %>
<% provide(:form_title, "Feed search") %>

<% if logged_in? %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<%= render 'shared/user_info' %>
		</section>
		<section class="stats">
			<%= render 'shared/stats' %>
		</section>
		<section class="micropost_form">
			<%= render 'shared/micropost_form' %>
		</section>
	</aside>
	<div class="col-md-8">
		<h3>Micropost Feed</h3>
		<%= render 'shared/search_form' %>
		<%= render 'shared/feed' %>
	</div>
</div>
<% else %>
<div class="center jumbotron">
	<h1>Welecome to twitter like app</h1>
	<h2>This is the home page for the twitter like app</h2>
	<%= link_to "Sign up now", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>