config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  #static_pages
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  #users
  get    '/signup',  to: 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  #sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  #accountactivations
  resources :accout_activations, only: [:edit]
  #password_resets
  resources :password_resets,    only: [:new, :create, :edit, :update]
  #microposts
  resources :microposts,         only: [:show, :create, :destroy]
  #relationships
  resources :relationships,      only: [:create, :destroy]
  #likes
  resources :likes,              only: [:create, :destroy]
  #comments
  resources :comments,           only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
	has_many :microposts, dependent: :destroy
	has_many :active_relationships, class_name: "Relationship",
									foreign_key: "follower_id",
									dependent: :destroy
	has_many :passive_relationships, class_name: "Relationship",
									  foreign_key: "followed_id",
									  dependent: :destroy
	has_many :likes, dependent: :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower
	has_many :comments, dependent: :destroy
	attr_accessor :remember_token, :activation_token, :reset_token
	before_save   :downcase_email
	before_create :create_activation_digest
	validates  :name, presence: true, length:  { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates  :email, presence: true, length: { maximum: 255 },
					 format: { with: VALID_EMAIL_REGEX},
					 uniqueness: { case_sensitive: false}
	validates  :password, presence: true, length: { minimum: 6}, allow_nil: true
	has_secure_password

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
	end

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def authenticated?(attribute, token)
		digest = self.send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

	def activate
		self.update_attribute(:activated, true)
		self.update_attribute(:activated_at, Time.zone.now)
	end

	def send_activation_email
		UserMailer.accout_activation(self).deliver_now
	end

	def create_reset_digest
		self.reset_token = User.new_token
		self.update_attribute(:reset_digest, User.digest(self.reset_token))
		self.update_attribute(:reset_sent_at, Time.zone.now)
	end

	def send_password_reset_email
		UserMailer.password_reset(self).deliver_now
	end

	def password_reset_expired?
		reset_sent_at < 2.hours.ago	
	end

	def feed
		following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    	Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
	end

	def follow(other_user)
		following << other_user
	end

	def unfollow(other_user)
		active_relationships.find_by(followed_id: other_user.id).destroy
	end

	def following?(other_user)
		following.include?(other_user)
	end

	def User.search(search)
		if search
			self.where(['name LIKE ?', "%#{search}%"])
		else
			self.all
		end
	end
	private

		def downcase_email
			self.email = email.downcase
		end

		def create_activation_digest
			self.activation_token = User.new_token
			self.activation_digest = User.digest(activation_token)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account"
      redirect_to root_url
  	else
  		render "new"
  	end
  end

  def show
  	@user = User.find_by(id: params[:id])
    @microposts = @user.microposts.paginate(page: params[:page]).search(params[:search])
  end

  def edit
   
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile update!!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.where(activated: true).paginate(page: params[:page]).search(params[:search]) 
  end

  def destroy
    User.find_by(id: params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render "show_follow"
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render "show_follow"
  end

  private

 	  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
	<div><%= hidden_field_tag :followed_id, @user.id %></div>
	<%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
 	<div id="follow_form">
 		<% if current_user.following?(@user) %>
 			<%= render 'unfollow' %>
 		<% else %>
 			<%= render 'follow' %>
 		<% end %>
 	</div>
 <% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name, class: "form-control" %>

<%= f.label :email %>
<%= f.email_field :email, class: "form-control" %>

<%= f.label :password %>
<%= f.password_field :password, class: "form-control" %>

<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation, class: "form-control" %>

<%=f.submit yield(:btn_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete}, remote: true) do |f| %>
	<%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for(user, size: 50) %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
	 | <%= link_to 'delete', user_path(user), method: :delete, data: { confirm: "You sure?"} %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:btn_text, "Save change") %>
<h1>Edit</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form' %>
    <div class="gravatar-edit">
    	<%= gravatar_for @user %>
    	<a href="http://gravatar.com/emails" target="_blank">Change</a>
    </div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All users") %>
<% provide(:form_path, users_path) %>
<% provide(:form_title, "User search") %>
<h1>All users</h1>

<%= will_paginate %>
<!-- ここに検索機能を追加する　-->
<div class="user_search">
	<%= render 'shared/search_form' %>
</div>
<ul class="users">
	<% @users.each do |user| %>
		<%= render user %>
	<% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<% provide(:btn_text, "Create my account") %>
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'form' %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<% provide(:form_path, user_path(@user.id)) %>
<% provide(:form_title, "Micropost search") %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%= gravatar_for(@user, size: 80) %>
				<%= @user.name %>
			</h1>
		</section>
		<section class="stats">
			<%= render 'shared/stats' %>
		</section>
	</aside>
	<div class="col-md-8">
		<%= render 'follow_form' if logged_in? %>
		<% if @user.microposts.any? %>
			<h3>Microposts (<%= @user.microposts.count %>) </h3>
			<%= render 'shared/search_form' %>
			<ol class="microposts">
				<%= render @microposts %>
 			</ol>
 			<%= will_paginate @microposts %>
		<% end %>
	</div>
</div>	

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
				<%= gravatar_for(@user, size: 80) %>
				<h1><%= @user.name %></h1>
				<span><%= link_to 'View my profile', @user %></span>
				<span><b>Microposts:<%= @user.microposts.count %></b>
		</section>
		<section class="stats">
			<%= render 'shared/stats' %>
			<% if @users.any? %>
				<div class="user_avatars">
					<% @users.each do |user| %>
						<%= link_to gravatar_for(user, size: 30), user %> 
					<% end %>
				</div>
			<% end %>
		</section>
	</aside>
	<div class="col-md-8">
		<h3><%= @title %></h3>
		<% if @users.any? %>
			<ul class="users follow">
				<%= render @users %>
			</ul>
			<%= will_paginate %>
		<% end %>
	</div>
</div>